[package]
name = "formula-first-light"
version = "0.0.1"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
formula-core = { path = "../formula-core" }
formula-engine = { path = "../formula-engine" }

[dev-dependencies]
formula-check = { path = "../formula-check" }
formula-packages = { path = "../formula-packages" }
formula-realize = { path = "../formula-realize" }
formula-store = { path = "../formula-store" }
tempfile.workspace = true
