pub mod affine_polynomial;
pub mod campaign;
pub mod candidate_space;
pub mod compiler;
pub mod decomposition;
pub mod discovery;
pub mod obligation;
pub mod observational;
pub mod query;
pub mod reduction;
pub mod region;
pub mod replay;
pub mod representation;
pub mod result_bundle;
pub mod reuse;
pub mod route_space;
pub mod search_policy;
pub mod self_expansion;
pub mod theory_profile;
pub mod work_cell;

pub const CRATE_ROLE: &str = "query campaign and search orchestration";
