pub mod bootstrap;
pub mod bootstrap_verifier;
pub mod envelope;
pub mod exact_arithmetic;
pub mod federation_verifier;
pub mod first_light;
pub mod gf2;
pub mod identity;
pub mod modular_arithmetic;
pub mod polynomial;
pub mod promotion;
pub mod proof_evolution;
pub mod realization;
pub mod router;
pub mod rsa_public;
pub mod sat_lrat;
pub mod self_expansion;
pub mod self_expansion_verifier;
pub mod u8;
pub mod verdict;
pub mod verifier_equivalence;

pub const CRATE_ROLE: &str = "independent evidence checking boundary";
